/*

Query que o Heber pediu para reunião 

QUANTIDADE DE PACIENTES MARCADOS QUE JA GEROU 
 CLAUDIO 10 PACIENTES MARCADOS DIA
 

*/

SELECT CD_PRESTADOR PRESTADOR,
       COUNT(IT.CD_AGENDA_CENTRAL) QUANTIDADE,
       DT_AGENDA DIA
  FROM it_agenda_central IT
  JOIN agenda_central AG
    ON IT.CD_AGENDA_CENTRAL = AG.CD_AGENDA_CENTRAL
 WHERE IT.HR_AGENDA >= SYSDATE
   AND AG.CD_UNIDADE_ATENDIMENTO IN (3, 6, 7)
   AND IT.NM_PACIENTE IS NOT NULL
 GROUP BY DT_AGENDA, CD_PRESTADOR
 ORDER BY DT_AGENDA ASC

-- Esta gerando valores nulos (EDITAR A QUERY)
